<h2>Sign up using this form</h2>


<div class="flash-messages">
        <?= $this->flashSession->output() ?>
</div>

<?php echo $this->tag->form("signup/register"); ?>



<!-- 
是 Phalcon 框架的一个方法，等於生成HTML <input type="text">。
傳遞给它的數組參数用於設置該輸入字段的屬性，比如以下的 name 和 class。
= echo $this->tag->textField(["name","class" => "form-control"]);
-->
    <div class="form-group">
        <label for="name">Name</label>

        <!-- render()渲染出來 -->
        <?php echo $form->render(
            "name",
        ); ?>

    </div>

    <div class="form-group">
        <label for="email">E-Mail</label>
        <?php echo $form->render(
            "email",
        ); ?>
    </div>

    <div class="form-group">
        <?php echo $form->render(
            "submit",
        ); ?>
    </div>

</form>

<!-- 回到 localhost 的 link -->
<?php echo $this->tag->linkTo(
    '',
    'Go Back'
);
?>