<?php

echo "<h1>Hello!</h1>";


echo $this->tag->linkTo([
    'signup',
    'Sign Up Here!',
    'class' => 'btn btn-outline-secondary',
    'style' => 'margin: 10px'
]);
echo $this->tag->linkTo([
    'test',
    'Edit',
    'class' => 'btn btn-outline-secondary',
    'style' => 'margin: 10px'
])

?>

<table  class="table table-hover">
    <thead class="thead-dark">
        <tr>
            <th scope="col">id</th>
            <th scope="col">name</th>
            <th scope="col">email</th>
        </tr>
    </thead>

    <?php foreach ($users as $user): ?>
    <tr>
        <td><?php echo $user->id; ?></td>
        <td><?php echo $user->name; ?></td>
        <td><?php echo $user->email; ?></td>
    </tr>
    <?php endforeach; ?>
</table>