<?php echo "<h1>Edit</h1>"; ?>
<?php echo $this->flashSession->output() ?>
<?php echo $this->tag->form("test/update") ?>
<!-- "test/update" 是表單提交的目標 URL 或路由。告訴表單數據提交到 TestController 控制器的 updateAction。 -->
<div class="form-group">
    <label for="name">Name</label>
    <?php echo $this->tag->textField(["name","class" => "form-control"]); ?>
</div>

<div class="form-group">
    <label for="email">Email</label>
    <?php echo $this->tag->textField(["email","class" => "form-control"]); ?>
</div>

<div class="form-group">
    <?php echo $this->tag->submitButton(["Update", 'class' => "btn btn-outline-secondary"]); ?>
</div>
<?php echo $this->tag->linkTo(
    '/test',
    'Go Back'
);
?>