<?php echo "<h1>Edit</h1>"; ?>

<div class="form-group">
    <label for="name">Name</label>
    <?php echo $this->tag->textField(["name","class" => "form-control"]); ?>
</div>

<div class="form-group">
    <label for="email">Email</label>
    <?php echo $this->tag->textField(["email","class" => "form-control"]); ?>
</div>

<?php

echo $this->tag->linkTo([
    'test',
    '確認',
    'class' => 'btn btn-outline-secondary',
]);
?>